export const SUCHANFRAGEN: string[] = [
    "Affoltern Anzeiger Schule",
    "Volksschule Kanton Zürich",
    "Schulpflege Zürich",
    "Schulleitung Kanton Zürich Konflikt",
    "Bildungsdirektion Zürich",
    "Schulpräsident Zürich Rücktritt Wahl",
    "Volksschulamt Zürich",
    "Schulhaus Zürich Bauprojekt",
    "Primarschule Zürich",
    "Sekundarschule Zürich",
    "Sonderschule Zürich",
    "Schulqualität Zürich",
    "Lehrpersonen Zürich Kündigung",
    "Schule Zürich Gewalt Mobbing",
    "Schule Zürich Digitalisierung",
    "Schule Zürich Finanzen Budget",
];
